'use client'

import { useEffect, useState } from 'react'
import { motion, useInView, useMotionValue, useSpring } from 'framer-motion'
import { ArrowUpRight, BarChart3, Bell, BookOpen, Check, ChevronDown, CircleDollarSign, FileText, Menu, MessageCircle, ShieldCheck, Sparkles, TrendingUp, Users, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const chartData = [{ month: 'Apr', amount: 62 }, { month: 'May', amount: 71 }, { month: 'Jun', amount: 68 }, { month: 'Jul', amount: 79 }, { month: 'Aug', amount: 76 }, { month: 'Sep', amount: 87 }]
const students = [['Aarav Sharma', '9B', '₹48,000', '₹48,000', '₹0', 'Paid'], ['Ananya Iyer', '8A', '₹42,000', '₹30,000', '₹12,000', 'Pending'], ['Vihaan Mehta', '10C', '₹55,000', '₹20,000', '₹35,000', 'Overdue'], ['Diya Kapoor', '7A', '₹38,000', '₹38,000', '₹0', 'Paid']]

const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: 'easeOut' } } }
function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.14 }}>{children}</motion.div> }
function CountUp({ value }: { value: number }) { const ref = useMotionValue(0); const spring = useSpring(ref, { duration: 1200 }); const [display, setDisplay] = useState(0); const node = useInView({ once: true }); useEffect(() => { if (node) ref.set(value) }, [node, ref, value]); useEffect(() => spring.on('change', v => setDisplay(Math.round(v))), [spring]); return <>{display}</> }
function Button({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <button className={`inline-flex items-center justify-center gap-2 rounded-[10px] px-5 py-2.5 text-xs font-medium transition hover:-translate-y-0.5 ${light ? 'bg-white text-slate-900 hover:bg-blue-50' : 'bg-slate-950 text-white hover:bg-blue-700'}`}>{children}</button> }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p> }
function MockShell({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`mock-shell shadow-card rounded-[7px] ${className}`}><div className="mock-bar"><span className="flex gap-1"><i/><i/><i/></span><span className="text-[9px] text-slate-400">EduFinance AI / dashboard</span><span className="size-2 rounded-full bg-blue-500"/></div>{children}</div> }

function HeroArt() { return <div className="hero-art" aria-hidden="true"><div className="sun"/><div className="cloud cloud-a"/><div className="cloud cloud-b"/><div className="cloud cloud-c"/><svg className="hero-hills" viewBox="0 0 1200 300" preserveAspectRatio="none"><path d="M0 210C180 120 320 175 470 145c185-38 240-98 390-55 125 36 220 32 340-38v248H0Z" fill="#16A34A"/><path d="M0 240c150-80 285-28 440-76 180-56 315-42 430 18 120 61 210 29 330-43v161H0Z" fill="#22C55E"/></svg><div className="school"><div className="school-roof"/><div className="school-body"><div className="school-columns"><i/><i/><i/><i/></div><div className="school-door"/></div></div><div className="hill hill-back"/><div className="hill hill-front"/><div className="coin coin-a">₹</div><div className="coin coin-b">₹</div><div className="chart-bars"><i/><i/><i/><i/></div><motion.div className="hero-stat stat-one" animate={{ y: [0, -10, 0] }} transition={{ duration: 3.5, repeat: Infinity, ease: 'easeInOut', delay: 0 }}><b>Collection rate</b><strong>87% <em>▲ 6%</em></strong></motion.div><motion.div className="hero-stat stat-two" animate={{ y: [0, -10, 0] }} transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut', delay: .3 }}><b>Overdue — Class 9B</b><strong>₹1,24,000</strong></motion.div><motion.div className="hero-stat stat-three" animate={{ y: [0, -10, 0] }} transition={{ duration: 4.5, repeat: Infinity, ease: 'easeInOut', delay: .6 }}><b>Cash collected</b><strong>₹42.8L <em>▲ 12%</em></strong></motion.div></div> }

function DashboardPreview() { return <MockShell className="dashboard-preview"><div className="mock-content"><div className="flex items-center justify-between"><div><p className="text-[10px] text-slate-400">Good morning, Priya</p><h3 className="text-sm font-semibold">School overview</h3></div><span className="rounded-md bg-blue-50 px-2 py-1 text-[9px] text-blue-700">September 2026⌄</span></div><div className="grid grid-cols-3 gap-2 py-4"><div className="metric"><span>Total collected</span><b>₹<CountUp value={42.8}/>L</b><em>+12.4%</em></div><div className="metric"><span>Collection rate</span><b>87%</b><em>+6.1%</em></div><div className="metric"><span>Outstanding</span><b>₹8.4L</b><em className="!text-amber-600">Needs action</em></div></div><div className="grid gap-4 md:grid-cols-[1.2fr_1fr]"><div className="chart-card"><div className="flex justify-between"><b>Monthly collection</b><span className="text-[9px] text-slate-400">Last 6 months</span></div><div className="h-36 pt-3"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><CartesianGrid stroke="#eef2f7" vertical={false}/><XAxis dataKey="month" tick={{fontSize:9, fill:'#94a3b8'}} axisLine={false} tickLine={false}/><YAxis hide/><Tooltip contentStyle={{fontSize:10, borderRadius:8, border:'1px solid #e5e7eb'}}/><Area type="monotone" dataKey="amount" stroke="#2563eb" fill="#dbeafe" strokeWidth={2} /></AreaChart></ResponsiveContainer></div></div><div className="chart-card"><b>Recent activity</b><div className="mt-3 flex flex-col gap-3">{['Fee received · Aarav Sharma','Reminder sent · Class 9B','Receipt generated · Diya Kapoor'].map((x, i) => <div key={x} className="flex items-center gap-2 text-[10px] text-slate-500"><span className={`size-5 rounded-full ${i === 1 ? 'bg-amber-100' : 'bg-blue-100'}`}/>{x}<span className="ml-auto text-[8px]">Today</span></div>)}</div></div></div></div></MockShell> }

function TableMock() { return <MockShell className="table-mock"><div className="mock-content"><div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-semibold">Student fee records</h3><p className="text-[9px] text-slate-400">1,248 students · Updated just now</p></div><span className="rounded-md bg-slate-950 px-2 py-1 text-[9px] text-white">+ Add payment</span></div><div className="overflow-x-auto"><table><thead><tr>{['Student','Class','Total','Paid','Outstanding','Status'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{students.map(s => <tr key={s[0]}>{s.map((v, i) => <td key={i}>{i === 5 ? <span className={`status ${v.toLowerCase()}`}>{v}</span> : v}</td>)}</tr>)}</tbody></table></div></div></MockShell> }

const chapters = [{ num: '1.0', label: 'COLLECT', title: 'Get every fee record into one place', copy: 'Bring student fees, structures and payments together so your team always has one reliable source of truth.', items: ['Student fee records','Class-wise fee structure','Payment entry','Receipts'], panel: <TableMock/> }, { num: '2.0', label: 'UNDERSTAND', title: 'See where the money actually is', copy: 'Turn everyday transactions into a clear view of collection health, pending dues and class-wise trends.', items: ['Collection rate','Pending vs overdue','Class-wise trends','Monthly collection'], panel: <DashboardPreview/> }, { num: '3.0', label: 'ACT', title: 'Act before dues become defaults', copy: 'AI finds the signal in your finance data and recommends the next best action for your team.', items: ['AI insight feed','Risk flags','Payment reminders','Reports'], panel: <MockShell><div className="mock-content flex flex-col gap-3"><div><h3 className="text-sm font-semibold">AI insights</h3><p className="text-[9px] text-slate-400">Your school, understood.</p></div>{['Class 9B outstanding is 2.3x school average — send reminder','14 students crossed due date this week','Collection down 8% vs last month'].map((x, i) => <div className="insight" key={x}><span className={i === 1 ? 'bg-amber-100 text-amber-700' : 'bg-blue-100 text-blue-700'}>{i === 1 ? '!' : '✦'}</span><p>{x}<small>{i === 0 ? 'Recommended action · 2 min ago' : 'Detected by EduFinance AI'}</small></p><ArrowUpRight /></div>)}</div></MockShell> }]

export default function EduFinanceLanding() { const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false); useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 24); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, []); return <main className="overflow-hidden bg-white text-slate-950">
  <nav className={`site-nav ${scrolled ? 'is-scrolled' : ''}`}><div className="container nav-inner"><a className="wordmark" href="#top">EduFinance <span>AI</span></a><div className={`nav-links ${menu ? 'is-open' : ''}`}><a className="nav-product" href="#product">Product</a><i/><a className="nav-schools" href="#schools">For Schools</a><i/><a className="nav-parents" href="#parents">For Parents</a><i/><a className="nav-insights" href="#insights">AI Insights</a></div><div className="nav-actions"><button className="login">Log in</button><Button>Open demo <ArrowUpRight data-icon="inline-end"/></Button></div><button className="menu-btn" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">{menu ? <X/> : <Menu/>}</button></div></nav>
  <section id="top" className="hero"><motion.img className="hero-image" src="/hero-scene.png" alt="Pixel-art park scene with a laptop and notebook" initial={{ scale: 1.05 }} animate={{ scale: 1 }} transition={{ duration: 1.5, ease: 'easeOut' }}/><div className="hero-overlay"/><HeroArt/><div className="hero-copy"><Eyebrow>THE FINANCIAL OS FOR SCHOOLS</Eyebrow><h1>Run your school&apos;s<br/><span>finances with AI</span></h1><p>One platform for fee collection, pending dues, parent communication and financial intelligence.</p><div className="flex flex-wrap justify-center gap-2"><Button>Open admin demo <ArrowUpRight/></Button><Button light>Open parent demo <ArrowUpRight/></Button></div></div></section>
  <section className="logo-strip"><div className="container"><div className="logo-row"><span>GREENWOOD <b>HIGH</b></span><span>ST. MARY&apos;S</span><span>SUNRISE <b>PUBLIC SCHOOL</b></span><span>DELHI MODERN <b>ACADEMY</b></span></div><p>Built for schools managing 500–5,000 students</p></div></section>
  <motion.section id="product" className="section ambient-section" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .12 }} variants={{ visible: { transition: { staggerChildren: .08 } } }}><div className="container text-center"><Eyebrow>THE PROBLEM, SOLVED</Eyebrow><h2>Fee data lives in registers,<br/><span>WhatsApp and spreadsheets</span></h2><p className="section-sub">EduFinance AI puts it in one financial system.</p><DashboardPreview/><div className="three-up"><div><b>Centralised fee ledger</b><p>Every student, class and payment in one record.</p></div><div><b>Parent in the loop</b><p>Parents see status, history and receipts, no calls.</p></div><div><b>AI insights</b><p>Surface overdue risk and collection drops before they hurt.</p></div></div></div></motion.section>
  <motion.section id="how" className="section muted" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .1 }} variants={{ visible: { transition: { staggerChildren: .08 } } }}><div className="container"><div className="text-center"><Eyebrow>HOW IT WORKS</Eyebrow><h2>Learn how to start a company<br/><span>without starting from scratch.</span></h2></div><div className="chapters">{chapters.map((c) => <div className="chapter" key={c.num}><div className="chapter-copy"><Eyebrow>{c.num} — {c.label}</Eyebrow><h3>{c.title}</h3><p>{c.copy}</p><ol>{c.items.map((x, i) => <li key={x}><span>{c.num[0]}.{i + 1}</span>{x}</li>)}</ol></div><div className="chapter-panel"><div className={`chapter-scene scene-${c.num[0]}`} aria-hidden="true"><div className="scene-folder"/><div className="scene-chart"><i/><i/><i/><i/></div><div className="scene-bell">!</div></div>{c.panel}</div></div>)}</div></div></motion.section>
  <motion.section id="schools" className="section ambient-section roles-section" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .12 }} variants={{ visible: { transition: { staggerChildren: .08 } } }}><div className="container"><div className="text-center"><Eyebrow>BUILT FOR EVERY ROLE</Eyebrow><h2>One system, two simple<br/><span>experiences.</span></h2></div><div className="role-grid"><RoleCard id="admin" icon={<ShieldCheck/>} title="For School Admins" copy="Make every rupee visible, accountable and easier to act on." items={['Dashboard & collection overview','Student financial profiles','Payments, reports & receipts','AI insights & notifications']} /><RoleCard id="parents" icon={<Users/>} title="For Parents" copy="Give families a clear, calm way to stay on top of school fees." items={['Fee status and due dates','Total, paid & outstanding','Payment history & receipts','Helpful reminders']} /></div></div></motion.section>
  <Reveal><section className="industry-section"><div className="container text-center"><Eyebrow>BUILT ACROSS INDUSTRIES</Eyebrow><h2>One system for every<br/><span>school finance moment.</span></h2><div className="word-grid"><span>FEE</span> <mark>COLLECTION</mark> · <span>PARENT</span> <mark>PORTAL</mark> · <mark>AI</mark> <span>INSIGHTS</span> · <span>OVERDUE</span> <mark>ALERTS</mark> · <span>RECEIPTS</span> · <span>REPORTS</span><br/><span>COLLECTION</span> · <mark>PARENT</mark> <span>PORTAL</span> · <span>AI</span> <mark>INSIGHTS</mark> · <mark>OVERDUE</mark> <span>ALERTS</span> · <span>RECEIPTS</span> · <span>REPORTS</span></div></div></section></Reveal>
  <motion.section id="insights" className="ai-band immersive-band" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .12 }} variants={{ visible: { transition: { staggerChildren: .08 } } }}><div className="container text-center"><Eyebrow>INTELLIGENCE, BUILT IN</Eyebrow><h2>Financial intelligence,<br/><span>not just a fee register</span></h2><div className="pillars"><div><Sparkles/><b>Detects patterns</b><p>Finds collection drops early.</p></div><div><TrendingUp/><b>Predicts risk</b><p>Flags likely overdue fees.</p></div><div><Bell/><b>Recommends action</b><p>Tells you what to do next.</p></div></div><div className="ai-screen"><MockShell><div className="mock-content"><div className="flex justify-between"><div><h3 className="text-sm font-semibold">AI Insights</h3><p className="text-[9px] text-slate-400">Tuesday, 20 September 2026</p></div><span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] text-blue-700">12 new insights</span></div><div className="grid gap-3 pt-4 md:grid-cols-3"><div className="ai-stat"><CircleDollarSign/><b>87%</b><span>collection health</span></div><div className="ai-stat"><BarChart3/><b>₹8.4L</b><span>to be collected</span></div><div className="ai-stat"><MessageCircle/><b>24</b><span>recommended actions</span></div></div><div className="mt-4 rounded-xl border border-blue-100 bg-blue-50/60 p-4 text-left"><span className="text-[9px] font-semibold uppercase tracking-wider text-blue-700">Priority insight</span><p className="mt-1 text-xs font-medium">Class 9B outstanding is 2.3x the school average.</p><p className="mt-1 text-[10px] text-slate-500">Send a parent reminder to 18 families before Friday.</p></div></div></MockShell></div></div></motion.section>
  <Reveal><section className="section final"><div className="container"><div className="final-card"><div><Eyebrow>READY WHEN YOU ARE</Eyebrow><h2>Run your school&apos;s<br/><span>finances with AI</span></h2><p>See what a calmer, clearer school finance system looks like.</p><Button>Open demo <ArrowUpRight/></Button></div></div><footer><div className="wordmark">EduFinance <span>AI</span><p>Financial clarity for every school.</p></div><div className="footer-links"><div><b>Product</b><a href="#product">Overview</a><a href="#how">How it works</a><a href="#insights">AI Insights</a></div><div><b>For Schools</b><a href="#schools">Admin demo</a><a href="#schools">Capabilities</a></div><div><b>For Parents</b><a href="#parents">Parent demo</a><a href="#parents">Fee status</a></div><div><b>Resources</b><a href="#top">Contact</a><a href="#top">Privacy</a></div></div></footer><div className="bottom-line">Prototype — frontend only. Built for Smart School FinTech Innovation Challenge 2026.</div></div></section></Reveal>
</main> }

function RoleCard({ id, icon, title, copy, items }: { id: string; icon: React.ReactNode; title: string; copy: string; items: string[] }) { return <div className="role-card" id={id}><div className="role-card-copy"><div className="role-icon">{icon}</div><h3>{title}</h3><p>{copy}</p><ul>{items.map(x => <li key={x}><Check/>{x}</li>)}</ul><a href="#top">Open demo <ArrowUpRight/></a></div><div className="role-thumb"><div className="thumb-top"/><div className="thumb-lines"><i/><i/><i/><i/><i/></div><div className="thumb-chart"/></div></div> }
